// <auto-generated />
using System;
using AquaCulture.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AquaCulture.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260511064451_RecreateFishFarmTable2")]
    partial class RecreateFishFarmTable2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AquaCulture.Domain.Entities.FishFarm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("HasBarge")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("NoOfCages")
                        .HasColumnType("integer");

                    b.Property<string>("PictureUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("fish_farm", (string)null);
                });

            modelBuilder.Entity("AquaCulture.Domain.Entities.Worker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("CertifiedUntil")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("FishFarmId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Position")
                        .HasColumnType("text");

                    b.Property<string>("ProfileImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("FishFarmId");

                    b.ToTable("worker", (string)null);
                });

            modelBuilder.Entity("AquaCulture.Domain.Entities.FishFarm", b =>
                {
                    b.OwnsOne("AquaCulture.Domain.Entities.GeoLocation", "GpsLocation", b1 =>
                        {
                            b1.Property<Guid>("FishFarmId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Latitude")
                                .HasColumnType("decimal(9,4)");

                            b1.Property<decimal>("Longitude")
                                .HasColumnType("decimal(9,4)");

                            b1.HasKey("FishFarmId");

                            b1.HasIndex("Latitude", "Longitude")
                                .IsUnique();

                            b1.ToTable("fish_farm");

                            b1.WithOwner()
                                .HasForeignKey("FishFarmId");
                        });

                    b.Navigation("GpsLocation")
                        .IsRequired();
                });

            modelBuilder.Entity("AquaCulture.Domain.Entities.Worker", b =>
                {
                    b.HasOne("AquaCulture.Domain.Entities.FishFarm", "FishFarm")
                        .WithMany("Workers")
                        .HasForeignKey("FishFarmId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("FishFarm");
                });

            modelBuilder.Entity("AquaCulture.Domain.Entities.FishFarm", b =>
                {
                    b.Navigation("Workers");
                });
#pragma warning restore 612, 618
        }
    }
}
